/**
 * The weekly DATA posts — LinkedIn drafts made only of counts from the store.
 *
 * WHY. A hand-drafted "10 employers that posted the most engineering
 * internships in India since July" took 8,395 impressions in a day on
 * 17 Sep 2026 — twice what the personal account does in its best measured
 * WEEK (§12). The format is a ranked list with real numbers, one link and no
 * sell, and every number in it already exists in the store. This makes that
 * a standing weekly draft rather than an afternoon's spreadsheet.
 *
 * SEVEN FORMATS, ONE WINDOW. Each is a different cut of the same rows — the
 * last `WINDOW_DAYS` on one board — so the numbers move week to week and the
 * post never repeats itself. All seven are written to one page with a card
 * image each; `pickOfWeek` names one so the page has an answer to "which",
 * and he can ignore it.
 *
 * THE RULES ARE /report's (§11): every number carries its denominator, a
 * count too thin to say anything is DROPPED rather than weakened, nothing is
 * generated by a model, and the sources are never named — the post says
 * "we tracked", never where. "Stated a stipend" is the site's own
 * `stipendText` rule over the published projection: `₹0` and a bare number
 * are not a stipend. Employers are those on TODAY's watchlist, re-derived
 * through `matchCompany` exactly as publish does — the stored
 * `company_matched` column is what the row matched when it was stored, and
 * a 15 Sep draft counted STEMpedia's 13 postings that way after the employer
 * had been de-listed.
 *
 * FULL-TIME GRADUATE ROLES ARE OUT. They are collected on purpose and the
 * board files them under their own tab, but a post that says "internships"
 * and counts them is the "Campus … (Full-Time)" mistake of 15 Sep again.
 */
import { matchCompany, isBlockedCompany } from './config.js';
import { resolveRowRegion, regionOf, regionPath } from './regions.js';
import { isFullTimeRole, stipendText, companySlug, RECORD_MIN_POSTINGS, SITE } from './pages.js';
import { formatStipend } from './extract.js';
import { boldSans, utmUrl } from './postgen.js';
import { applicantCount } from './telegram.js';
import { canonicalCity } from './facets.js';
import { whatsappFor, telegramFor } from './channels.js';
import { weekKey } from './weekly.js';

export const WINDOW_DAYS = 30;
/* Below these the sentence is not a finding. Dropped, not weakened. */
export const MIN_ROWS = 40;
export const MIN_COUNTED = 30;
export const FORMATS = ['employers', 'newcomers', 'queue', 'stipends', 'timing', 'cities', 'skills', 'spotlight'];
export const CAMPAIGN = 'data-post';

const pct = (n, of) => (of ? Math.round((100 * n) / of) : 0);
const ratio = (n, of) => (n > 0 ? Math.max(2, Math.round(of / n)) : null);
const sortDesc = (m) => [...m].sort((a, b) => b[1] - a[1] || String(a[0]).localeCompare(String(b[0])));

/**
 * The board's engineering internships, annotated, split into the window and
 * the whole history. History is what "first time" means: the earliest row on
 * the board is when tracking began, and a newcomer is an employer with no row
 * before the window.
 */
export function dataRows(store, cfg, { region = 'IN', now = Date.now(), days = WINDOW_DAYS } = {}) {
  const code = String(region).toUpperCase();
  const since = now - days * 86_400_000;
  const raw = store.db.prepare('SELECT * FROM jobs WHERE is_tech = 1 AND suppressed_reason IS NULL').all();
  const history = [];
  for (const r of raw) {
    if (resolveRowRegion(r) !== code) continue;
    if (isBlockedCompany(r.company)) continue;
    const matched = matchCompany(r.company, cfg.watchlist);
    if (!matched) continue;
    if (isFullTimeRole({ employmentType: r.employment_type })) continue;
    const stipend = formatStipend({
      min: r.stipend_min, max: r.stipend_max, currency: r.stipend_currency, period: r.stipend_period,
    }) || r.salary_text || null;
    history.push({
      id: String(r.job_id),
      employer: matched,
      title: String(r.title ?? ''),
      firstSeen: Number(r.first_seen_at) || 0,
      postedAt: Number(r.posted_at) || null,
      ats: String(r.job_id).startsWith('ats:'),
      stated: Boolean(stipendText({ stipend })),
      monthlyInr: (r.stipend_currency === 'INR' && r.stipend_period === 'month' && Number(r.stipend_min) > 0) ? Number(r.stipend_min) : null,
      applicants: String(r.job_id).startsWith('ats:') ? null : applicantCount(r.applicants),
      city: foldCity(canonicalCity(r.location) || ''),
      mode: String(r.workplace_type ?? '').toLowerCase().replace(/[^a-z]/g, ''),
      skills: safeList(r.skills),
    });
  }
  history.sort((a, b) => a.firstSeen - b.firstSeen);
  const rows = history.filter((r) => r.firstSeen > since && r.firstSeen <= now);
  const trackedSince = history.length ? history[0].firstSeen : null;
  return { region: code, rows, history, since, now, days, trackedSince };
}

/* One name per city for a COUNT. canonicalCity strips trailing noise for a
   facet slug and deliberately leaves the spelling alone; a ranked list that
   shows Bengaluru and Bangalore as two entries is wrong in a way a reader
   spots at once. Only the spellings the store actually holds. */
const CITY_FOLD = { bangalore: 'Bengaluru', 'bangalore urban': 'Bengaluru', 'bengaluru urban': 'Bengaluru', 'bangalore rural': 'Bengaluru', gurgaon: 'Gurugram', 'new delhi': 'Delhi', bombay: 'Mumbai', 'navi mumbai': 'Mumbai', 'greater noida': 'Noida', 'thane': 'Mumbai', 'secunderabad': 'Hyderabad' };
export function foldCity(city) {
  const k = String(city ?? '').trim().toLowerCase();
  return CITY_FOLD[k] ?? String(city ?? '').trim();
}

function safeList(json) {
  try { const v = JSON.parse(json || '[]'); return Array.isArray(v) ? v.map(String) : []; } catch { return []; }
}

/* ---------------------------------------------------------------- formats */

function link(cfg, region, path, content) {
  return utmUrl(`${SITE}${regionPath(region)}${path}`, { campaign: CAMPAIGN, content, source: 'linkedin', medium: 'social' }, cfg);
}
const placeName = (region) => regionOf(region)?.name ?? region;
const hashtags = (...t) => t.map((x) => `#${x}`).join(' ');

/** 1. Who posted the most. */
export function employersPost(data, cfg) {
  const { rows, region, days } = data;
  if (rows.length < MIN_ROWS) return null;
  const by = new Map();
  const titles = new Map();
  for (const r of rows) {
    by.set(r.employer, (by.get(r.employer) ?? 0) + 1);
    if (!titles.has(r.employer)) titles.set(r.employer, new Set());
    titles.get(r.employer).add(r.title.toLowerCase());
  }
  const top = sortDesc(by).slice(0, 10);
  if (top.length < 5) return null;
  const where = placeName(region);
  const head = `The ${top.length} employers that posted the most engineering internships in ${where} in the last ${days} days:`;
  const lines = top.map(([c, n], i) => `${i + 1}. ${c} — ${n}`);
  const multi = top.filter(([c, n]) => n > titles.get(c).size).length;
  const post = [
    boldSans(head), '',
    ...lines, '',
    multi
      ? `Some of these post the same role in several cities, so ${top[0][1]} postings isn't ${top[0][1]} different jobs. But it does tell you who is actively taking interns right now.`
      : 'It tells you who is actively taking interns right now.',
    '',
    `Every one of them has a page showing what they've posted, month by month, and whether they ever stated pay:`,
    link(cfg, region, '/companies', 'employers'),
    '',
    hashtags('internships', 'hiring', 'engineering', 'placements'),
  ].join('\n');
  return {
    key: 'employers',
    title: `Who's hiring: the ${top.length} busiest employers`,
    post,
    stats: { rows: rows.length, employers: by.size, listed: top.length, top: top.map(([c, n]) => ({ employer: c, postings: n, titles: titles.get(c).size })) },
    notes: `${rows.length} internships from ${by.size} employers in the window. Ties break alphabetically. ${multi} of the ${top.length} post more roles than they have distinct titles.`,
    card: {
      eyebrow: `${where} · last ${days} days`,
      headline: `Who's hiring the most engineering interns`,
      rows: top.map(([c, n]) => ({ label: c, value: String(n), share: n / top[0][1] })),
      band: 'BE EARLY.',
    },
  };
}

/** 2. Who posted for the FIRST time. */
export function newcomersPost(data, cfg) {
  const { rows, history, region, days, since, trackedSince } = data;
  if (rows.length < MIN_ROWS) return null;
  const before = new Set(history.filter((r) => r.firstSeen <= since).map((r) => r.employer));
  const by = new Map();
  for (const r of rows) if (!before.has(r.employer)) by.set(r.employer, (by.get(r.employer) ?? 0) + 1);
  const fresh = sortDesc(by);
  if (fresh.length < 8) return null;
  const listed = fresh.slice(0, 12);
  const where = placeName(region);
  const startMonth = trackedSince ? new Date(trackedSince).toLocaleString('en-GB', { month: 'long', timeZone: regionOf(region)?.timeZone ?? 'Asia/Kolkata' }) : null;
  const head = `${fresh.length} employers posted their first engineering internship in ${where} in the last ${days} days.`;
  const post = [
    boldSans(head), '',
    `First since we started tracking${startMonth ? ` in ${startMonth}` : ''}, that is — not first ever. But if you've been refreshing the same five careers pages, these are the ones you're not watching:`,
    '',
    ...listed.map(([c, n]) => `→ ${c}${n > 1 ? ` (${n})` : ''}`),
    fresh.length > listed.length ? `…and ${fresh.length - listed.length} more.` : '',
    '',
    `All ${fresh.length} are on the board, each with a page of what they've posted:`,
    link(cfg, region, '/companies', 'newcomers'),
    '',
    hashtags('internships', 'hiring', 'engineeringstudents', 'placements'),
  ].filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
  return {
    key: 'newcomers',
    title: `${fresh.length} employers hiring interns for the first time`,
    post,
    stats: { rows: rows.length, newcomers: fresh.length, listed: listed.map(([c, n]) => ({ employer: c, postings: n })), trackedSince },
    notes: `A newcomer has no row on the board before the window opened (${new Date(since).toISOString().slice(0, 10)}); tracking began ${trackedSince ? new Date(trackedSince).toISOString().slice(0, 10) : '—'}. Listed by postings in the window, then name.`,
    card: {
      eyebrow: `${where} · last ${days} days`,
      headline: `${fresh.length} employers posted their first internship here`,
      rows: listed.slice(0, 10).map(([c, n]) => ({ label: c, value: n > 1 ? String(n) : '', share: n / listed[0][1] })),
      band: 'NEW THIS MONTH.',
    },
  };
}

/** 3. How fast the queue forms. */
export function queuePost(data, cfg) {
  const { rows, region, days } = data;
  /* dataRows already gives a careers-board row no count — the guard lives
     there, once, where the annotation is made. */
  const counted = rows.filter((r) => r.applicants != null);
  if (counted.length < MIN_COUNTED) return null;
  const bands = { none: 0, few: 0, some: 0, many: 0 };
  for (const r of counted) {
    if (r.applicants === 0) bands.none += 1;
    else if (r.applicants < 25) bands.few += 1;
    else if (r.applicants < 100) bands.some += 1;
    else bands.many += 1;
  }
  const n = counted.length;
  const oneIn = ratio(bands.many, n);
  const where = placeName(region);
  const head = oneIn
    ? `1 in ${oneIn} engineering internships in ${where} had 100+ applicants within hours of going up.`
    : `Most engineering internships in ${where} still had a short queue when we found them.`;
  const wa = whatsappFor(region, cfg);
  const tg = telegramFor(region, cfg);
  const post = [
    boldSans(head), '',
    `We see most postings within a few hours of them going live. Of the ${n} we counted in the last ${days} days, at that moment:`,
    '',
    `👥 100+ applicants — ${bands.many} (${pct(bands.many, n)}%)`,
    `👥 25 to 99 — ${bands.some} (${pct(bands.some, n)}%)`,
    `👥 1 to 24 — ${bands.few} (${pct(bands.few, n)}%)`,
    `👥 Nobody yet — ${bands.none} (${pct(bands.none, n)}%)`,
    '',
    `${pct(bands.none + bands.few, n)}% had under 25 applicants. That is the window. It closes in a day.`,
    '',
    wa ? `Every new role, the minute it's listed → ${wa.url}` : (tg ? `Every new role, the minute it's listed → ${tg.url}` : null),
    `The board → ${link(cfg, region, '/', 'queue')}`,
    '',
    hashtags('internships', 'jobsearch', 'freshers', 'engineering'),
  ].filter((l) => l !== null).join('\n');
  return {
    key: 'queue',
    title: 'How fast the queue forms',
    post,
    stats: { counted: n, bands, cutoffs: { many: 100, some: 25 }, oneIn, pct: { many: pct(bands.many, n), some: pct(bands.some, n), few: pct(bands.few, n), none: pct(bands.none, n), under25: pct(bands.none + bands.few, n) } },
    notes: `Applicant counts are the posting's own figure at FIRST sighting, never refreshed; careers-board rows carry none and are excluded. "Over 100" counts as 100+.`,
    card: {
      eyebrow: `${where} · last ${days} days · ${n} postings`,
      headline: oneIn ? `1 in ${oneIn} had 100+ applicants within hours` : 'The queue forms in a day',
      rows: [
        { label: '100+ applicants', value: `${pct(bands.many, n)}%`, share: bands.many / n },
        { label: '25 – 99', value: `${pct(bands.some, n)}%`, share: bands.some / n },
        { label: '1 – 24', value: `${pct(bands.few, n)}%`, share: bands.few / n },
        { label: 'Nobody yet', value: `${pct(bands.none, n)}%`, share: bands.none / n },
      ],
      band: 'BE EARLY.',
    },
  };
}

/** 4. Who says what they pay. */
export function stipendsPost(data, cfg) {
  const { rows, region, days } = data;
  if (rows.length < MIN_ROWS) return null;
  const stated = rows.filter((r) => r.stated);
  const by = new Map();
  for (const r of rows) by.set(r.employer, (by.get(r.employer) ?? 0) + 1);
  const top = sortDesc(by).slice(0, 10);
  const topStated = top.filter(([c]) => rows.some((r) => r.employer === c && r.stated)).length;
  const topPostings = top.reduce((s, [, n]) => s + n, 0);
  const monthly = rows.map((r) => r.monthlyInr).filter((v) => v != null).sort((a, b) => a - b);
  const median = monthly.length >= 5 ? monthly[Math.floor(monthly.length / 2)] : null;
  const oneIn = ratio(stated.length, rows.length);
  const where = placeName(region);
  const head = `Only ${stated.length} of ${rows.length} engineering internships in ${where} stated a stipend in the last ${days} days.`;
  const post = [
    boldSans(head), '',
    oneIn ? `About 1 in ${oneIn}.` : 'None.', '',
    `The ${top.length} employers that posted the most — ${top.slice(0, 5).map(([c]) => c).join(', ')} and ${top.length - 5} more — posted ${topPostings} between them. ${topStated === 0 ? 'Not one listing carried a figure.' : `${topStated} of them stated pay on at least one listing.`}`,
    '',
    `That doesn't mean they don't pay — most do. It means you usually find out after the interview, not before you apply.`,
    median ? `\nWhere a monthly figure was stated (${monthly.length} listings), the middle one was ₹${median.toLocaleString('en-IN')}.` : '',
    '',
    `→ Ask about the stipend on the first HR call, not after the offer.`,
    `→ Check an employer's hiring record before you apply — every company page shows whether it has ever stated pay:`,
    link(cfg, region, '/companies', 'stipends'),
    '',
    hashtags('internships', 'engineeringstudents', 'stipend', 'placements'),
  ].filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
  return {
    key: 'stipends',
    title: 'Who says what they pay',
    post,
    stats: { rows: rows.length, stated: stated.length, oneIn, top: top.length, topPostings, topStated, monthlyFigures: monthly.length, medianMonthlyInr: median },
    notes: `"Stated" is the site's own stipendText rule over the published projection: ₹0, a bare number and a missing period are not a stipend. Median is over INR monthly minimums only.`,
    card: {
      eyebrow: `${where} · last ${days} days`,
      headline: `${stated.length} of ${rows.length} internships stated a stipend`,
      rows: [
        { label: 'Stated a stipend', value: `${pct(stated.length, rows.length)}%`, share: stated.length / rows.length },
        { label: 'Did not', value: `${pct(rows.length - stated.length, rows.length)}%`, share: (rows.length - stated.length) / rows.length },
        ...(median ? [{ label: 'Median monthly, where stated', value: `₹${median.toLocaleString('en-IN')}`, share: 0 }] : []),
      ],
      band: 'ASK EARLY.',
    },
  };
}

/** 5. When they go up. */
export function timingPost(data, cfg) {
  const { rows, region, days } = data;
  const zone = regionOf(region)?.timeZone ?? 'Asia/Kolkata';
  const live = rows.filter((r) => !r.ats && r.postedAt);
  if (live.length < MIN_COUNTED) return null;
  const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const byDay = new Array(7).fill(0);
  const byBlock = { morning: 0, afternoon: 0, evening: 0, night: 0 };
  for (const r of live) {
    const local = new Date(new Date(r.postedAt).toLocaleString('en-US', { timeZone: zone }));
    byDay[local.getDay()] += 1;
    const h = new Date(new Date(r.firstSeen).toLocaleString('en-US', { timeZone: zone })).getHours();
    if (h >= 6 && h < 12) byBlock.morning += 1;
    else if (h >= 12 && h < 18) byBlock.afternoon += 1;
    else if (h >= 18) byBlock.evening += 1;
    else byBlock.night += 1;
  }
  const n = live.length;
  const ranked = DAYS.map((d, i) => [d, byDay[i]]).sort((a, b) => b[1] - a[1]);
  const weekend = byDay[0] + byDay[6];
  const block = Object.entries(byBlock).sort((a, b) => b[1] - a[1])[0];
  const blockLabel = { morning: '6 am and noon', afternoon: 'noon and 6 pm', evening: '6 pm and midnight', night: 'midnight and 6 am' }[block[0]];
  const where = placeName(region);
  const head = `${ranked[0][0]} is when engineering internships in ${where} go up.`;
  const post = [
    boldSans(head), '',
    `Of the ${n} we caught within hours of being posted in the last ${days} days:`,
    '',
    `📅 ${ranked[0][0]} — ${ranked[0][1]}. ${ranked[1][0]} and ${ranked[2][0]} next (${ranked[1][1]} and ${ranked[2][1]}).`,
    `📅 Saturday and Sunday together — ${weekend}. ${weekend ? `About 1 in ${ratio(weekend, n)}.` : ''}`.trim(),
    `🕐 ${pct(block[1], n)}% appeared between ${blockLabel}.`,
    '',
    `So if you check once a day, check ${block[0] === 'evening' ? 'in the evening' : block[0] === 'afternoon' ? 'after lunch' : `in the ${block[0]}`}, ${ranked[0][0]} to ${ranked[2][0]}.`,
    '',
    `Or don't check at all — every new role goes out the minute it's listed:`,
    link(cfg, region, '/alerts', 'timing'),
    '',
    hashtags('internships', 'jobsearch', 'freshers', 'engineering'),
  ].join('\n');
  return {
    key: 'timing',
    title: 'When internships go up',
    post,
    stats: { counted: n, byDay: Object.fromEntries(DAYS.map((d, i) => [d, byDay[i]])), weekend, weekendOneIn: ratio(weekend, n), byBlock, blockPct: pct(block[1], n) },
    notes: `Weekday from the posting's own date in ${zone}; hour block from first sighting (the sweep window is ~3 h, so read it as "within a few hours of"). Careers-board rows are excluded: their first-sighting time is the poll, not the posting.`,
    card: {
      eyebrow: `${where} · last ${days} days · ${n} postings`,
      headline: `When internships go up`,
      rows: DAYS.slice(1).concat(DAYS.slice(0, 1)).map((d) => ({ label: d, value: String(byDay[DAYS.indexOf(d)]), share: byDay[DAYS.indexOf(d)] / (ranked[0][1] || 1) })),
      band: 'CHECK ' + (block[0] === 'afternoon' ? 'AFTER LUNCH.' : block[0].toUpperCase() + 'S.'),
    },
  };
}

/** 6. Where they are. */
export function citiesPost(data, cfg) {
  const { rows, region, days } = data;
  if (rows.length < MIN_ROWS) return null;
  const by = new Map();
  for (const r of rows) if (r.city) by.set(r.city, (by.get(r.city) ?? 0) + 1);
  const top = sortDesc(by).slice(0, 6);
  if (top.length < 4) return null;
  const modes = { onsite: 0, hybrid: 0, remote: 0 };
  for (const r of rows) if (r.mode in modes) modes[r.mode] += 1;
  const n = rows.length;
  const where = placeName(region);
  const head = `${pct(top[0][1], n)}% of engineering internships in ${where} are in ${top[0][0]}. ${pct(modes.remote, n)}% are remote.`;
  const post = [
    boldSans(head), '',
    `Of the ${n} we tracked in the last ${days} days:`,
    '',
    ...top.map(([c, k]) => `📍 ${c} — ${k}${k === top[0][1] ? ` (${pct(k, n)}%)` : ''}`),
    '',
    `And how:`,
    `🏢 On-site — ${pct(modes.onsite, n)}%`,
    `🔀 Hybrid — ${pct(modes.hybrid, n)}%`,
    `🏠 Remote — ${pct(modes.remote, n)}%`,
    '',
    `If you're holding out for a remote engineering internship, the numbers say widen the search. If you can move to ${top[0][0]} for six months, that's ${pct(top[0][1], n) >= 40 ? 'close to half' : 'the biggest slice of'} the market.`,
    '',
    `Browse by city → ${link(cfg, region, '/locations', 'cities')}`,
    '',
    hashtags('internships', top[0][0].toLowerCase().replace(/[^a-z]/g, ''), 'engineeringstudents', 'placements'),
  ].join('\n');
  return {
    key: 'cities',
    title: 'Where the internships are',
    post,
    stats: { rows: n, cities: top.map(([c, k]) => ({ city: c, postings: k, pct: pct(k, n) })), modes, modePct: { onsite: pct(modes.onsite, n), hybrid: pct(modes.hybrid, n), remote: pct(modes.remote, n) }, modeStated: modes.onsite + modes.hybrid + modes.remote },
    notes: `City by the site's canonicalCity fold (Bengaluru/Bangalore, Gurugram/Gurgaon). Mode percentages are over ALL ${n} rows; ${n - (modes.onsite + modes.hybrid + modes.remote)} state none.`,
    card: {
      eyebrow: `${where} · last ${days} days · ${n} postings`,
      headline: `Where the internships are`,
      rows: top.map(([c, k]) => ({ label: c, value: `${pct(k, n)}%`, share: k / top[0][1] })),
      band: `${pct(modes.remote, n)}% REMOTE.`,
    },
  };
}

/* Casing a skill the way its community writes it. Short tokens are not all
   acronyms — "git" is Git — so the initialisms are listed rather than guessed. */
const ACRONYMS = new Set(['sql', 'aws', 'gcp', 'api', 'apis', 'rest', 'css', 'html', 'php', 'ios', 'ml', 'ai', 'nlp', 'etl', 'ci/cd', 'qa', 'ui', 'ux', 'c++', 'c#', 'js', 'ts', 'sdk', 'llm', 'llms', 'rtl', 'fpga', 'soc', 'asic', 'vlsi', 'iot', 'jvm', 'sql server', 'nosql', 'mysql', 'postgresql', 'mongodb', 'graphql', 'http', 'tcp/ip', 'oop', 'dsa', 'cnn', 'gan', 'gpu', 'cuda', 'aws lambda', 'ci', 'cd', 'excel', 'linux', 'unix']);
const PROPER = { git: 'Git', github: 'GitHub', gitlab: 'GitLab', javascript: 'JavaScript', typescript: 'TypeScript', 'node.js': 'Node.js', nodejs: 'Node.js', 'react.js': 'React', reactjs: 'React', 'next.js': 'Next.js', 'vue.js': 'Vue.js', pytorch: 'PyTorch', tensorflow: 'TensorFlow', opencv: 'OpenCV', 'scikit-learn': 'scikit-learn', matlab: 'MATLAB', mongodb: 'MongoDB', mysql: 'MySQL', postgresql: 'PostgreSQL', nosql: 'NoSQL', graphql: 'GraphQL', docker: 'Docker', kubernetes: 'Kubernetes', linux: 'Linux', excel: 'Excel', 'power bi': 'Power BI', 'spring boot': 'Spring Boot', 'machine learning': 'Machine learning', 'data structures': 'Data structures', 'system design': 'System design' };
export function prettySkill(s) {
  const k = String(s ?? '').trim().toLowerCase();
  if (PROPER[k]) return PROPER[k];
  if (ACRONYMS.has(k)) return k.toUpperCase();
  return k.replace(/(^|\s)([a-z])/g, (m, sp, c) => sp + c.toUpperCase());
}

/** 7. What they ask for. */
export function skillsPost(data, cfg) {
  const { rows, region, days } = data;
  const withSkills = rows.filter((r) => r.skills.length);
  if (withSkills.length < MIN_ROWS) return null;
  const by = new Map();
  for (const r of withSkills) for (const s of new Set(r.skills)) by.set(s, (by.get(s) ?? 0) + 1);
  const top = sortDesc(by).slice(0, 8);
  const n = withSkills.length;
  const where = placeName(region);
  const pretty = (s) => prettySkill(s);
  const head = `${pretty(top[0][0])} is in ${pct(top[0][1], n)}% of engineering internship postings in ${where}.`;
  const post = [
    boldSans(head), '',
    `The skills named most often across ${n} postings in the last ${days} days:`,
    '',
    ...top.map(([s, k], i) => `${i + 1}. ${pretty(s)} — ${pct(k, n)}%`),
    '',
    `Nobody expects all of these from an intern. But a resume that names none of the top three is competing on something else.`,
    '',
    `Every skill has a page listing the open roles that ask for it → ${link(cfg, region, '/skills', 'skills')}`,
    '',
    hashtags('internships', 'engineeringstudents', pretty(top[0][0]).toLowerCase().replace(/[^a-z0-9]/g, ''), 'placements'),
  ].join('\n');
  return {
    key: 'skills',
    title: 'The skills postings ask for',
    post,
    stats: { rows: n, top: top.map(([s, k]) => ({ skill: s, postings: k, pct: pct(k, n) })) },
    notes: `Denominator is postings with at least one extracted skill (${n} of ${rows.length}); a skill counts once per posting.`,
    card: {
      eyebrow: `${where} · last ${days} days · ${n} postings`,
      headline: `What the postings ask for`,
      rows: top.map(([s, k]) => ({ label: pretty(s), value: `${pct(k, n)}%`, share: k / top[0][1] })),
      band: 'NAME THE TOP THREE.',
    },
  };
}

/** 8. One employer's hiring record — the hub's `hiringRecord`, as a post. */

/**
 * Which employer to spotlight: the busiest in the window with a record worth
 * telling (RECORD_MIN_POSTINGS all-time), skipping any in `exclude` — the
 * names already spotlighted, so the same employer is not the subject two
 * weeks running. Null when nobody qualifies.
 */
export function chooseSpotlight(data, { exclude = [] } = {}) {
  const skip = new Set(exclude.map((e) => String(e).toLowerCase()));
  const inWindow = new Map();
  for (const r of data.rows) inWindow.set(r.employer, (inWindow.get(r.employer) ?? 0) + 1);
  const allTime = new Map();
  for (const r of data.history) allTime.set(r.employer, (allTime.get(r.employer) ?? 0) + 1);
  const ranked = sortDesc(inWindow).filter(([c]) => (allTime.get(c) ?? 0) >= RECORD_MIN_POSTINGS && !skip.has(c.toLowerCase()));
  return ranked.length ? ranked[0][0] : null;
}

const monthKeyOf = (ms, zone) => {
  const d = new Date(new Date(ms).toLocaleString('en-US', { timeZone: zone }));
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
};
const monthLabelOf = (key, { long = false } = {}) => new Date(Date.UTC(Number(key.slice(0, 4)), Number(key.slice(5, 7)) - 1, 15))
  .toLocaleString('en-US', { month: long ? 'long' : 'short', timeZone: 'UTC' });   // en-US: "Sep", where en-GB gives "Sept"

export function spotlightPost(data, cfg, { employer, publishedIds = null } = {}) {
  const { history, region, now, trackedSince } = data;
  if (!employer) return null;
  const rows = history.filter((r) => r.employer === employer && r.firstSeen <= now);
  const n = rows.length;
  if (n < RECORD_MIN_POSTINGS) return null;
  const zone = regionOf(region)?.timeZone ?? 'Asia/Kolkata';
  const where = placeName(region);

  /* Months with zeros, from the later of the employer's first dated posting
     and the board's first sighting, to now — the hub's rule. Postings dated
     before the board watched are counted and said, not drawn. */
  const dated = rows.map((r) => r.postedAt ?? r.firstSeen).filter(Boolean);
  const firstKey = monthKeyOf(Math.min(...dated), zone);
  const sinceKey = trackedSince ? monthKeyOf(trackedSince, zone) : firstKey;
  const startKey = firstKey > sinceKey ? firstKey : sinceKey;
  const untilKey = monthKeyOf(now, zone);
  const counts = new Map();
  let before = 0;
  for (const ms of dated) {
    const k = monthKeyOf(ms, zone);
    if (k >= startKey && k <= untilKey) counts.set(k, (counts.get(k) ?? 0) + 1);
    else if (k < startKey) before += 1;
  }
  const months = [];
  {
    let [y, m] = startKey.split('-').map(Number);
    for (let guard = 0; guard < 36; guard++) {
      const k = `${y}-${String(m).padStart(2, '0')}`;
      if (k > untilKey) break;
      months.push({ key: k, label: monthLabelOf(k) + (k === untilKey ? ' so far' : ''), count: counts.get(k) ?? 0 });
      m += 1; if (m > 12) { m = 1; y += 1; }
    }
  }

  const titles = new Map();
  for (const r of rows) titles.set(r.title, (titles.get(r.title) ?? 0) + 1);
  const topTitle = sortDesc(titles)[0];
  const cities = sortDesc(rows.reduce((m, r) => (r.city ? m.set(r.city, (m.get(r.city) ?? 0) + 1) : m), new Map())).slice(0, 3);
  const stated = rows.filter((r) => r.stated).length;
  const monthly = rows.map((r) => r.monthlyInr).filter((v) => v != null).sort((a, b) => a - b);
  const median = monthly.length >= 3 ? monthly[Math.floor(monthly.length / 2)] : null;
  const payWord = region === 'IN' ? 'a stipend' : 'pay';

  /* Standing, coarse and honest: `within` counts employers with AT LEAST this
     many postings, itself included, so a tie at the tenth place cannot make
     twelve employers "one of the ten". */
  /* Over the SAME rows the count uses (first seen by `now`), or an employer
     can out-rank itself: a mutation test found `within` counting a row that
     `n` did not. */
  const allTime = new Map();
  for (const r of history) if (r.firstSeen <= now) allTime.set(r.employer, (allTime.get(r.employer) ?? 0) + 1);
  const of = allTime.size;
  const within = [...allTime.values()].filter((v) => v >= n).length;
  const standing = within <= 10
    ? `One of the 10 most active employers of engineering interns we track in ${where}, out of ${of}.`
    : within <= Math.ceil(of / 4)
      ? `In the busiest quarter of the ${of} employers we track in ${where}.`
      : null;

  const open = publishedIds ? rows.filter((r) => publishedIds.has(r.id)).length : null;
  const firstLabel = monthLabelOf(startKey, { long: true });
  const head = `${employer} has posted ${n} engineering internship${n === 1 ? '' : 's'} in ${where} since ${firstLabel}.`;
  const monthLine = months.map((m) => `${m.label.replace(' so far', '')} ${m.count}${m.label.endsWith('so far') ? ' so far' : ''}`).join(' · ');
  const post = [
    boldSans(head), '',
    `📅 By month: ${monthLine}${before ? ` (and ${before} posted before we began tracking)` : ''}.`,
    topTitle ? `🧭 Most often: "${topTitle[0]}"${topTitle[1] > 1 ? ` — ${topTitle[1]} times` : ''}, ${titles.size} distinct title${titles.size === 1 ? '' : 's'} in all.` : null,
    cities.length ? `📍 ${cities.map(([c, k]) => `${c} (${k})`).join(', ')}.` : null,
    stated === 0
      ? `💰 None of the ${n} stated ${payWord}.`
      : `💰 ${stated === n ? `All ${n}` : `${stated} of the ${n}`} stated ${payWord}${median ? ` — where monthly, the middle figure was ₹${median.toLocaleString('en-IN')}` : ''}.`,
    standing ? `🏁 ${standing}` : null,
    '',
    open != null
      ? (open ? `${open} open right now, with the whole record, month by month:` : `Nothing open at the moment — the record, and the next one the day it lands:`)
      : 'The whole record, month by month:',
    link(cfg, region, `/companies/${companySlug(employer)}`, 'spotlight'),
    '',
    hashtags('internships', companySlug(employer).replace(/[^a-z0-9]/g, ''), 'engineering', 'placements'),
  ].filter((l) => l !== null).join('\n');

  const cardRows = months.slice(-MAX_CARD_MONTHS);
  const top = Math.max(1, ...cardRows.map((m) => m.count));
  return {
    key: 'spotlight',
    title: `Employer spotlight: ${employer}`,
    post,
    stats: {
      employer, postings: n, months: Object.fromEntries(months.map((m) => [m.key, m.count])), before,
      titles: titles.size, topTitle: topTitle ? { title: topTitle[0], times: topTitle[1] } : null,
      cities: cities.map(([c, k]) => ({ city: c, postings: k })), stated, monthlyFigures: monthly.length, medianMonthlyInr: median,
      standing: { within, of }, open,
    },
    notes: `${n} = every ${employer} engineering internship on the board since tracking began; months from the posting's own date (${zone}), zeros shown; standing counts employers with at least ${n} postings. "Open" is the published set at write time.`,
    card: {
      eyebrow: `${where} · ${employer} · since ${firstLabel}`,
      headline: `${employer}: ${n} internships${stated === 0 ? ', none stated pay' : `, ${stated} stated pay`}`,
      rows: cardRows.map((m) => ({ label: m.label, value: String(m.count), share: m.count / top })),
      band: open ? `${open} OPEN NOW.` : 'ON THE BOARD.',
    },
  };
}
const MAX_CARD_MONTHS = 10;

const COMPOSERS = { employers: employersPost, newcomers: newcomersPost, queue: queuePost, stipends: stipendsPost, timing: timingPost, cities: citiesPost, skills: skillsPost };

/** Every format that has enough data this week, in FORMATS order. */
export function dataPosts(store, cfg, { spotlight = {}, ...opts } = {}) {
  const data = dataRows(store, cfg, opts);
  const posts = [];
  for (const key of FORMATS) {
    const p = key === 'spotlight'
      ? spotlightPost(data, cfg, { employer: spotlight.employer ?? chooseSpotlight(data, { exclude: spotlight.exclude ?? [] }), publishedIds: spotlight.publishedIds ?? null })
      : COMPOSERS[key](data, cfg);
    if (p) posts.push({ ...p, region: data.region, window: { since: data.since, now: data.now, days: data.days } });
  }
  return { region: data.region, rows: data.rows.length, employers: new Set(data.rows.map((r) => r.employer)).size, posts };
}

/**
 * Which of the week's formats to lead with — rotated by ISO week so the same
 * cut is not suggested two weeks running. A suggestion, not a rule.
 */
export function pickOfWeek(posts, now = Date.now(), zone = 'Asia/Kolkata') {
  if (!posts.length) return null;
  const week = Number(weekKey(now, zone).split('-W')[1]) || 0;
  return posts[week % posts.length].key;
}

/**
 * Due once a week, on or after `hour` on `weekday` in the board's own zone —
 * the same shape as the roundup's `roundupDue`, and for the same reason: this
 * Mac sleeps, and a cron entry would simply be missed.
 */
export function dataPostDue(cfg, lastKey, now = Date.now(), region = 'IN') {
  const conf = cfg.postQueue?.dataPost ?? {};
  if (conf.enabled !== true) return false;
  const zone = regionOf(region)?.timeZone ?? 'Asia/Kolkata';
  const local = new Date(new Date(now).toLocaleString('en-US', { timeZone: zone }));
  if (local.getDay() !== (conf.weekday ?? 3)) return false;
  if (local.getHours() < (conf.hour ?? 10)) return false;
  return lastKey !== weekKey(now, zone);
}

export function dataPostRegions(cfg) {
  return (cfg.postQueue?.dataPost?.regions ?? ['IN']).map((r) => String(r).toUpperCase());
}
